version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_server_exchange_rate
    ports:
      - "6379:6379"
    environment:
      - REDIS_APPENDONLY=yes
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  mongo:
    image: mongo:7.0
    container_name: mongo_server_exchange_rate
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local

networks:
  redis_network:
    driver: bridge
  app_network:
    driver: bridge
