global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']

  - job_name: 'fiber-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
